# This is an example .meta-cnc.yaml file. This will allow Panhandler to consume this terraform project

# this is the name of this skillet, should be unique within a given repository
name: Cloud-Azure-AKS-Cluster

# label should be a human readable label that conveys what this skillet will do
label: Azure - AKS Cluster

# description is a longer more informative version of a label
description: This skillet deploys an Azure AKS container cluster.

# type instructs Panhandler how to consume this skillet
type: terraform

# extends allows you to include other skillets along with this one
extends:

# labels allow extensible configuration options per skillet type. For example, lables can be used to
# group multiple skillets of the same type (pan-os skillets labeled as version: 9.0 for example)
labels:
  terraform_provider: azure
  collection:
    - Azure
    - Containers

# Variables will be presented to the user via the Panhandler GUI. These values will then be passed to
# the terraform binary as '--var' options, thus overriding any tfvars entries.
# Variable names MUST match the names of the defined terraform variables
variables:
  - name: client_id
    description: Azure Application ID Service Principal
    default:
    type_hint: text
  - name: client_secret
    description: Azure Application ID Service Principal Password
    default:
    type_hint: text
  - name: resource_group_name
    description: Azure Resource Group (maximum 30 characters)
    default: CHANGEME-aks-cluster-rg
    type_hint: text
  - name: location
    description: Azure Region
    default: australiaeast
    type_hint: dropdown
    dd_list:
     - key: "West US"
       value: "westus"
     - key: "West US 2"
       value: "westus2"
     - key: "West Central US"
       value: "westcentralus"
     - key: "East US"
       value: "eastus"
     - key: "East US 2"
       value: "eastus2"
     - key: "Central US"
       value: "centralus"
     - key: "North Central US"
       value: "northcentralus"
     - key: "South Central US"
       value: "southcentralus"
     - key: "Canada Central"
       value: "canadacentral"
     - key: "Canada East"
       value: "canadaeast"
     - key: "UK West"
       value: "ukwest"
     - key: "UK South"
       value: "uksouth"
     - key: "North Europe"
       value: "northeurope"
     - key: "West Europe"
       value: "westeurope"
     - key: "Australia East"
       value: "australiaeast"
     - key: "Australia Southeast"
       value: "australiasoutheast"
     - key: "Australia Central"
       value: "australiacentral"
     - key: "Australia Central 2"
       value: "australiacentral2"
     - key: "East Asia"
       value: "eastasia"
     - key: "South East Asia"
       value: "southeastasia"
     - key: "Korea Central"
       value: "koreacentral"
     - key: "Korea South"
       value: "koreasouth"
     - key: "Japan West"
       value: "japanwest"
     - key: "Japan East"
       value: "japaneast"
     - key: "South India"
       value: "southindia"
     - key: "Central India"
       value: "centralindia"
     - key: "West India"
       value: "westindia"
     - key: "Brazil South"
       value: "brazilsouth"
     - key: "France Central"
       value: "francecentral"
     - key: "France South"
       value: "francesouth"
  - name: cluster_name
    description: AKS Cluster Name
    default: CHANGEME-aks-cluster-name (maximum 30 characters)
    type_hint: text
  - name: dns_prefix
    description: AKS Cluster DNS Prefix
    default: CHANGEME-aks-cluster-dns (maximum 30 characters)
    type_hint: text
  - name: agent_count
    description: Initial number of nodes which should exist in this Node Pool
    default: 3
    type_hint: text
  - name: vm_size
    description: AKS Cluster Instance Size
    default: Standard_DS2_v2
    type_hint: text
  - name: adminUsername
    description: AKS Cluster Admin Username
    default:
    type_hint: text
  - name: ssh_public_key
    description: AKS Cluster SSH Authorized Key
    default: ssh-rsa SomeKeyDataStringHere
    type_hint: text