# This is an example .meta-cnc.yaml file. This will allow Panhandler to consume this terraform project

# this is the name of this skillet, should be unique within a given repository
name: Cloud-Azure-AKS-Prisma-Cloud-Compute

# label should be a human readable label that conveys what this skillet will do
label: Prisma Cloud Compute Installation onto an Existing AKS Cluster

# description is a longer more informative version of a label
description: This skillet deploys Prisma Cloud Compute onto an existing Azure AKS container cluster.

# type instructs Panhandler how to consume this skillet
type: terraform

# extends allows you to include other skillets along with this one
extends:

# labels allow extensible configuration options per skillet type. For example, lables can be used to
# group multiple skillets of the same type (pan-os skillets labeled as version: 9.0 for example)
labels:
  terraform_provider: azure
  collection:
    - Azure
    - Containers

# Variables will be presented to the user via the Panhandler GUI. These values will then be passed to
# the terraform binary as '--var' options, thus overriding any tfvars entries.
# Variable names MUST match the names of the defined terraform variables
variables:
  - name: resource_group_name
    description: Existing Azure Resource Group Name
    default: 
    type_hint: text
  - name: cluster_name
    description: Existing AKS Cluster Name
    default: 
    type_hint: text
  - name: access_token
    description: Prisma Cloud Compute Access Token
    default: 
    type_hint: text
  - name: twistlock_license
    description: Prisma Cloud Compute License Key
    default:
    type_hint: text
  - name: twistlock_user
    description: Create Initial Prisma Cloud Compute Console User
    default:
    type_hint: text
  - name: twistlock_password
    description: Create Initial Prisma Cloud Compute Console User Password
    default: 
    type_hint: text